"""Tests for src/nlhe/archetypes.py.

Behavioral tests rather than unit tests: each test verifies that the
archetype produces sensible action distributions on canonical scenarios,
using the real bucket-equity calibration from
runs/archetype_design/bucket_equity_analysis.json.

If the calibration JSON is missing the tests skip rather than fail --
the calibration is regenerated by scripts/analyze_bucket_equity.py.
"""
import random
from pathlib import Path

import numpy as np
import pytest

from src.nlhe.actions import DiscreteAction
from src.nlhe.archetypes import (
    NAMED_ARCHETYPES,
    ArchetypeName,
    EquityCalibration,
    OpponentPool,
    archetype_policy,
    derive_in_position,
)

CALIBRATION_PATH = Path("runs/archetype_design/bucket_equity_analysis.json")
N_DISCRETE_ACTIONS = 7  # FOLD, CALL, BET_33, BET_66, BET_100, BET_200, ALLIN


@pytest.fixture(scope="module")
def calibration():
    if not CALIBRATION_PATH.exists():
        pytest.skip(f"calibration not found at {CALIBRATION_PATH}")
    return EquityCalibration.load(CALIBRATION_PATH)


@pytest.fixture(scope="module")
def all_legal_mask():
    return np.ones(N_DISCRETE_ACTIONS, dtype=np.float32)


@pytest.fixture(scope="module")
def no_bet_mask():
    """Legal mask for "no bet to call" situation: FOLD is illegal, CALL=check
    is legal, all bets legal."""
    m = np.ones(N_DISCRETE_ACTIONS, dtype=np.float32)
    m[int(DiscreteAction.FOLD)] = 0.0
    return m


def _best_bucket(calibration, street):
    """Return the bucket ID with the highest equity on this street."""
    eqs = calibration.bucket_equity[street]
    return int(np.argmax(eqs))


def _worst_bucket(calibration, street):
    """Return the bucket ID with the lowest equity on this street."""
    eqs = calibration.bucket_equity[street]
    return int(np.argmin(eqs))


def _by_name(name):
    """Find the archetype profile by name."""
    for a in NAMED_ARCHETYPES:
        if a.name == name:
            return a
    raise KeyError(name)


# ----- Test 1: archetypes produce valid distributions -----

def test_policy_returns_valid_distribution(calibration, all_legal_mask):
    """Every archetype, on a representative scenario, returns a valid
    probability distribution over legal actions."""
    rng = random.Random(0)
    for arch in NAMED_ARCHETYPES:
        dist = archetype_policy(
            archetype=arch,
            calibration=calibration,
            street_idx=0,
            bucket_id=10,  # middle bucket
            in_position=True,
            pot_odds=0.33,
            stack_to_pot=20.0,  # deep
            legal_mask=all_legal_mask,
            facing_bet=True,
            rng=rng,
        )
        assert dist.shape == (N_DISCRETE_ACTIONS,)
        assert np.all(dist >= 0), f"{arch.name.name}: negative weights {dist}"
        assert np.isclose(dist.sum(), 1.0), \
            f"{arch.name.name}: distribution sums to {dist.sum()}, not 1.0"


# ----- Test 2: nit folds trash preflop, plays premiums -----

def test_nit_folds_trash_preflop(calibration, all_legal_mask):
    """Nit facing a preflop bet on the worst bucket should fold with very high probability."""
    nit = _by_name(ArchetypeName.NIT)
    worst = _worst_bucket(calibration, "preflop")
    rng = random.Random(0)
    dist = archetype_policy(
        archetype=nit, calibration=calibration,
        street_idx=0, bucket_id=worst,
        in_position=False, pot_odds=0.33, stack_to_pot=20.0,
        legal_mask=all_legal_mask, facing_bet=True, rng=rng,
    )
    assert dist[int(DiscreteAction.FOLD)] > 0.9, \
        f"nit on worst preflop bucket: fold prob {dist[int(DiscreteAction.FOLD)]:.3f}, " \
        f"expected > 0.9. Full dist: {dist}"


def test_nit_plays_premium_preflop(calibration, all_legal_mask):
    """Nit on the best preflop bucket should not fold to a preflop bet."""
    nit = _by_name(ArchetypeName.NIT)
    best = _best_bucket(calibration, "preflop")
    rng = random.Random(0)
    dist = archetype_policy(
        archetype=nit, calibration=calibration,
        street_idx=0, bucket_id=best,
        in_position=False, pot_odds=0.33, stack_to_pot=20.0,
        legal_mask=all_legal_mask, facing_bet=True, rng=rng,
    )
    assert dist[int(DiscreteAction.FOLD)] < 0.1, \
        f"nit on best preflop bucket: fold prob {dist[int(DiscreteAction.FOLD)]:.3f}, " \
        f"expected < 0.1. Full dist: {dist}"


# ----- Test 3: maniac plays trash, doesn't fold premiums -----

def test_maniac_plays_trash_preflop(calibration, all_legal_mask):
    """Maniac facing a preflop bet on the worst bucket should mostly call/raise."""
    maniac = _by_name(ArchetypeName.MANIAC)
    worst = _worst_bucket(calibration, "preflop")
    rng = random.Random(0)
    dist = archetype_policy(
        archetype=maniac, calibration=calibration,
        street_idx=0, bucket_id=worst,
        in_position=False, pot_odds=0.33, stack_to_pot=20.0,
        legal_mask=all_legal_mask, facing_bet=True, rng=rng,
    )
    assert dist[int(DiscreteAction.FOLD)] < 0.3, \
        f"maniac on worst preflop bucket: fold prob {dist[int(DiscreteAction.FOLD)]:.3f}, " \
        f"expected < 0.3. Full dist: {dist}"


# ----- Test 4: nit is tighter than maniac at every bucket -----

def test_nit_strictly_tighter_than_maniac_preflop(calibration, all_legal_mask):
    """At every preflop bucket, nit folds at least as much as maniac."""
    nit = _by_name(ArchetypeName.NIT)
    maniac = _by_name(ArchetypeName.MANIAC)
    rng = random.Random(0)
    n_buckets = len(calibration.bucket_equity["preflop"])
    nit_fold_above_maniac = 0
    for b in range(n_buckets):
        nit_dist = archetype_policy(
            archetype=nit, calibration=calibration,
            street_idx=0, bucket_id=b,
            in_position=False, pot_odds=0.33, stack_to_pot=20.0,
            legal_mask=all_legal_mask, facing_bet=True, rng=rng,
        )
        mn_dist = archetype_policy(
            archetype=maniac, calibration=calibration,
            street_idx=0, bucket_id=b,
            in_position=False, pot_odds=0.33, stack_to_pot=20.0,
            legal_mask=all_legal_mask, facing_bet=True, rng=rng,
        )
        if nit_dist[int(DiscreteAction.FOLD)] >= mn_dist[int(DiscreteAction.FOLD)]:
            nit_fold_above_maniac += 1
    # Allow occasional ties at the extremes but nit should win the vast majority.
    assert nit_fold_above_maniac >= n_buckets - 1, \
        f"nit folded more than maniac on only {nit_fold_above_maniac}/{n_buckets} buckets"


# ----- Test 5: aggression dial works as advertised -----

def test_aggression_drives_bet_vs_call_split(calibration, all_legal_mask):
    """At identical strong-hand scenario, MANIAC (aggression=0.95) should
    have more raise mass than STATION (aggression=0.2)."""
    maniac = _by_name(ArchetypeName.MANIAC)
    station = _by_name(ArchetypeName.STATION)
    best = _best_bucket(calibration, "flop")
    rng = random.Random(0)
    raise_actions = [
        int(DiscreteAction.BET_33), int(DiscreteAction.BET_66),
        int(DiscreteAction.BET_100), int(DiscreteAction.BET_200),
        int(DiscreteAction.ALLIN),
    ]
    mn_dist = archetype_policy(
        archetype=maniac, calibration=calibration,
        street_idx=1, bucket_id=best,
        in_position=True, pot_odds=0.5, stack_to_pot=10.0,
        legal_mask=all_legal_mask, facing_bet=True, rng=rng,
    )
    st_dist = archetype_policy(
        archetype=station, calibration=calibration,
        street_idx=1, bucket_id=best,
        in_position=True, pot_odds=0.5, stack_to_pot=10.0,
        legal_mask=all_legal_mask, facing_bet=True, rng=rng,
    )
    mn_raise = float(sum(mn_dist[a] for a in raise_actions))
    st_raise = float(sum(st_dist[a] for a in raise_actions))
    assert mn_raise > st_raise + 0.1, \
        f"maniac raise mass {mn_raise:.3f} not meaningfully > station {st_raise:.3f}"


# ----- Test 6: legal mask is honored -----

def test_legal_mask_zeros_illegal_actions(calibration):
    """If FOLD is masked illegal (no bet to fold to), no archetype should
    put weight on FOLD."""
    nit = _by_name(ArchetypeName.NIT)
    no_bet = np.ones(N_DISCRETE_ACTIONS, dtype=np.float32)
    no_bet[int(DiscreteAction.FOLD)] = 0.0
    rng = random.Random(0)
    # Below-threshold scenario where the archetype "wants" to fold:
    # nit on worst flop bucket with nothing to call.
    worst = _worst_bucket(calibration, "flop")
    dist = archetype_policy(
        archetype=nit, calibration=calibration,
        street_idx=1, bucket_id=worst,
        in_position=False, pot_odds=0.0, stack_to_pot=20.0,
        legal_mask=no_bet, facing_bet=False, rng=rng,
    )
    assert dist[int(DiscreteAction.FOLD)] == 0.0, \
        f"FOLD got weight {dist[int(DiscreteAction.FOLD)]} despite illegal mask"
    assert np.isclose(dist.sum(), 1.0), \
        f"distribution doesn't sum to 1 after masking: {dist.sum()}"


# ----- Test 7: position helper -----

def test_derive_in_position():
    # Preflop: player 1 acts first, player 0 acts second (in position).
    assert derive_in_position(street_idx=0, current_player=0) is True
    assert derive_in_position(street_idx=0, current_player=1) is False
    # Postflop: player 0 acts first, player 1 in position.
    for street in [1, 2, 3]:
        assert derive_in_position(street_idx=street, current_player=0) is False
        assert derive_in_position(street_idx=street, current_player=1) is True


# ----- Test 8: OpponentPool sampling -----

def test_opponent_pool_sampling(calibration):
    """archetype_mix=0.0 -> always self-play. archetype_mix=1.0 -> never None.
    archetype_mix=0.5 -> roughly half each over many samples."""
    rng = random.Random(0)
    pool_pure_selfplay = OpponentPool(calibration, archetype_mix=0.0)
    pool_pure_arch = OpponentPool(calibration, archetype_mix=1.0)
    pool_mixed = OpponentPool(calibration, archetype_mix=0.5)

    # Pure self-play: 100 samples should all be None.
    for _ in range(100):
        assert pool_pure_selfplay.sample_opponent(rng) is None

    # Pure archetype: 100 samples should never be None and span the pool.
    seen_archetypes = set()
    for _ in range(100):
        opp = pool_pure_arch.sample_opponent(rng)
        assert opp is not None
        seen_archetypes.add(opp.name)
    # All 5 archetypes should appear in 100 samples with high probability.
    assert len(seen_archetypes) == len(NAMED_ARCHETYPES), \
        f"expected to see all archetypes; saw {len(seen_archetypes)}"

    # Mixed: count Nones. Should be roughly half.
    n_none = sum(1 for _ in range(1000) if pool_mixed.sample_opponent(rng) is None)
    assert 400 <= n_none <= 600, \
        f"expected ~500 self-play samples in 1000 draws at mix=0.5, got {n_none}"
