"""Hand-engineered training opponents parameterized by tightness x aggression.

Each archetype is a stateless policy that maps (game state, bucket equity,
position, pot odds, stack/pot ratio) to a distribution over the 7 discrete
actions. They get plugged into solver._traverse to provide opponent style
diversity beyond pure self-play.

DATA-DERIVED THRESHOLDS
-----------------------
Tightness thresholds are quantiles of the bucket-equity population
distribution, computed once from the loaded card abstraction. "Nit plays
top 15% of hands preflop" means the nit's preflop fold threshold is the
bucket equity at the 85th percentile of the random-hand population --
not a hand-picked constant. The quantile table lives in
runs/archetype_design/bucket_equity_analysis.json and is regenerated by
scripts/analyze_bucket_equity.py.

When OCHS replaces EMD in A3, rerun the analysis and these archetypes
adapt automatically -- no code change needed, only the JSON regen.

KNOWN LIMITATION (A3 fix)
-------------------------
The current EMD bucket-equity table has ordering errors in the middle of
the equity range (e.g. AA and TT collide in the same preflop bucket, AKs
reads weaker than it should). Endpoints are roughly calibrated. The
quantile-based design tolerates this -- archetypes group hands as
"play / don't play" rather than picking exact equity thresholds, so
ordering errors in the middle don't change which broad category a hand
falls into. OCHS in A3 fixes the underlying ordering and the archetypes
inherit the improvement for free.

AGGRESSION (designed, not data-derived)
---------------------------------------
The aggression dial governs "given I'm in the pot, do I bet/raise vs
call/check." Values come from poker convention because we have no
labeled-action dataset to derive them empirically -- and shouldn't have
one, per the opponent anonymity principle (see DECISIONS.md).
"""

from __future__ import annotations

import json
import random
from dataclasses import dataclass
from enum import IntEnum
from pathlib import Path
from typing import Optional

import numpy as np

from src.nlhe.actions import DiscreteAction, GameStateView


# ----- Constants -----

N_DISCRETE_ACTIONS = len(DiscreteAction)
STREET_NAMES = ("preflop", "flop", "turn", "river")


# ----- Archetype identity -----

class ArchetypeName(IntEnum):
    NIT = 0
    TAG = 1
    LAG = 2
    STATION = 3
    MANIAC = 4


@dataclass(frozen=True)
class ArchetypeProfile:
    """Behavioral profile for one archetype.

    play_quantile_by_street: per-street quantile of the population equity
        distribution below which the archetype folds. Higher quantile =
        tighter (folds more). 0.85 means "fold below the 85th percentile",
        which means "play only the top 15% of hands".

    aggression: in [0, 1]. When in the pot and not facing a bet, fraction
        of decisions that are bet/raise vs check. When facing a bet,
        fraction of decisions that are raise vs call (given the hand is
        strong enough to continue).
    """
    name: ArchetypeName
    play_quantile_by_street: tuple[float, float, float, float]  # preflop, flop, turn, river
    aggression: float


# Quantile thresholds locked Session 6 from runs/archetype_design/bucket_equity_analysis.json.
# Each row is (preflop_q, flop_q, turn_q, river_q) where q is the population
# equity quantile below which the archetype folds.
NAMED_ARCHETYPES: tuple[ArchetypeProfile, ...] = (
    ArchetypeProfile(ArchetypeName.NIT,     (0.85, 0.75, 0.70, 0.60), aggression=0.25),
    ArchetypeProfile(ArchetypeName.TAG,     (0.70, 0.55, 0.50, 0.45), aggression=0.65),
    ArchetypeProfile(ArchetypeName.LAG,     (0.40, 0.30, 0.35, 0.40), aggression=0.85),
    ArchetypeProfile(ArchetypeName.STATION, (0.25, 0.15, 0.10, 0.05), aggression=0.20),
    ArchetypeProfile(ArchetypeName.MANIAC,  (0.05, 0.10, 0.20, 0.30), aggression=0.95),
)


# ----- Bucket equity table loader -----

@dataclass(frozen=True)
class EquityCalibration:
    """Loaded from bucket_equity_analysis.json.

    bucket_equity[street] -> array of mean equity per bucket id.
    quantile_thresholds[street][quantile_str] -> equity value at that quantile.
    """
    bucket_equity: dict[str, np.ndarray]
    quantile_thresholds: dict[str, dict[str, float]]

    @classmethod
    def load(cls, path: str | Path) -> "EquityCalibration":
        data = json.loads(Path(path).read_text())
        bucket_equity = {
            street: np.asarray(eqs, dtype=np.float32)
            for street, eqs in data["bucket_equity"].items()
        }
        return cls(
            bucket_equity=bucket_equity,
            quantile_thresholds=data["quantiles"],
        )

    def equity_threshold(self, street: str, quantile: float) -> float:
        """Return the equity value at the given quantile for a street.

        Linearly interpolates between the discrete quantile points in the JSON.
        """
        q_table = self.quantile_thresholds[street]
        # Quantile keys are "q05", "q15", ..., "q95"
        levels = sorted([(int(k[1:]) / 100.0, v) for k, v in q_table.items()])
        # Clamp to table range
        if quantile <= levels[0][0]:
            return levels[0][1]
        if quantile >= levels[-1][0]:
            return levels[-1][1]
        # Linear interpolation
        for i in range(len(levels) - 1):
            q0, v0 = levels[i]
            q1, v1 = levels[i + 1]
            if q0 <= quantile <= q1:
                t = (quantile - q0) / (q1 - q0)
                return v0 + t * (v1 - v0)
        # Unreachable given clamps above
        return levels[-1][1]


# ----- Position helper -----

def derive_in_position(street_idx: int, current_player: int) -> bool:
    """Return True if current_player is in position on this street.

    HUNL with firstPlayer="2 1 1 1" config:
      - Preflop: player 1 (SB/button) acts first, so player 0 (BB) is in position.
      - Postflop: player 0 acts first, so player 1 is in position.
    """
    if street_idx == 0:
        return current_player == 0
    return current_player == 1


# ----- Archetype policy -----

def archetype_policy(
    archetype: ArchetypeProfile,
    calibration: EquityCalibration,
    *,
    street_idx: int,
    bucket_id: int,
    in_position: bool,
    pot_odds: float,
    stack_to_pot: float,
    legal_mask: np.ndarray,
    facing_bet: bool,
    rng: random.Random,
) -> np.ndarray:
    """Return action distribution over the 7 DiscreteActions.

    Reads the archetype's per-street play quantile from the calibration to
    derive a fold threshold, compares it to this bucket's equity, and
    produces a distribution. The result is masked to legal actions and
    renormalized.

    Decision logic:
      1. Look up bucket equity. Below the play threshold -> fold (or check if free).
      2. Above threshold:
         - facing_bet: call vs raise governed by aggression.
         - not facing bet: check vs bet governed by aggression.
      3. Stack-depth modifier: short stacks collapse to push/fold.
    """
    street = STREET_NAMES[street_idx]
    bucket_equity = float(calibration.bucket_equity[street][bucket_id])
    play_quantile = archetype.play_quantile_by_street[street_idx]
    fold_threshold = calibration.equity_threshold(street, play_quantile)

    weights = np.zeros(N_DISCRETE_ACTIONS, dtype=np.float32)
    aggro = archetype.aggression

    # Short-stack mode: effectively all-in or fold once stack/pot drops below 2.
    short_stack_mode = stack_to_pot < 2.0

    if bucket_equity < fold_threshold:
        # Below play threshold. Fold if facing a bet, check otherwise.
        if facing_bet:
            weights[int(DiscreteAction.FOLD)] = 1.0
        else:
            # Check when there's nothing to call -> CALL slot.
            weights[int(DiscreteAction.CALL)] = 1.0
    else:
        # In the pot. Action depends on whether we're facing a bet.
        if facing_bet:
            # Call vs raise split.
            raise_prob = aggro
            call_prob = 1.0 - aggro

            # Stronger hands raise more often; weaker hands inside the "play"
            # band call more often. Modulate raise_prob by how far above the
            # fold threshold the equity is.
            equity_overshoot = (bucket_equity - fold_threshold) / max(1.0 - fold_threshold, 1e-6)
            raise_prob = raise_prob * (0.4 + 0.6 * equity_overshoot)
            call_prob = 1.0 - raise_prob

            if short_stack_mode:
                # Collapse to all-in vs fold for short stacks.
                weights[int(DiscreteAction.ALLIN)] = raise_prob
                weights[int(DiscreteAction.CALL)] = call_prob
            else:
                weights[int(DiscreteAction.CALL)] = call_prob
                # Distribute raise mass across bet sizes. Larger sizings get
                # less weight; aggression bumps the large-bet share.
                weights[int(DiscreteAction.BET_33)] = raise_prob * (0.5 - 0.2 * aggro)
                weights[int(DiscreteAction.BET_66)] = raise_prob * 0.3
                weights[int(DiscreteAction.BET_100)] = raise_prob * (0.15 + 0.1 * aggro)
                weights[int(DiscreteAction.BET_200)] = raise_prob * (0.05 + 0.1 * aggro)
        else:
            # Not facing a bet. Check vs bet split governed by aggression.
            bet_prob = aggro
            check_prob = 1.0 - aggro

            # Stronger hands bet more often within the play band.
            equity_overshoot = (bucket_equity - fold_threshold) / max(1.0 - fold_threshold, 1e-6)
            bet_prob = bet_prob * (0.3 + 0.7 * equity_overshoot)
            check_prob = 1.0 - bet_prob

            if short_stack_mode:
                weights[int(DiscreteAction.ALLIN)] = bet_prob
                # When checking is free, CALL is the check action (FOLD is illegal).
                weights[int(DiscreteAction.CALL)] = check_prob
            else:
                # CALL is the check action when nothing to call.
                weights[int(DiscreteAction.CALL)] = check_prob
                weights[int(DiscreteAction.BET_33)] = bet_prob * (0.5 - 0.2 * aggro)
                weights[int(DiscreteAction.BET_66)] = bet_prob * 0.3
                weights[int(DiscreteAction.BET_100)] = bet_prob * (0.15 + 0.1 * aggro)
                weights[int(DiscreteAction.BET_200)] = bet_prob * (0.05 + 0.1 * aggro)

    # In-position adjustment: in-position archetypes bet slightly more,
    # out-of-position they check more. Subtle nudge, not a structural change.
    if in_position and not facing_bet:
        # Shift 10% of check mass (CALL slot when free) to small bet.
        shift = 0.1 * weights[int(DiscreteAction.CALL)]
        weights[int(DiscreteAction.CALL)] -= shift
        weights[int(DiscreteAction.BET_33)] += shift

    # Mask to legal actions and renormalize.
    weights = weights * legal_mask
    total = weights.sum()
    if total > 0:
        weights = weights / total
    else:
        # Fallback: uniform over legal actions (shouldn't happen if mask has any 1s).
        n_legal = legal_mask.sum()
        if n_legal > 0:
            weights = legal_mask / n_legal
        else:
            # No legal actions -- caller's bug. Return zeros.
            weights = np.zeros(N_DISCRETE_ACTIONS, dtype=np.float32)

    return weights


# ----- Opponent pool -----

class OpponentPool:
    """Holds archetype profiles + equity calibration, samples opponents.

    Per-trajectory usage:
        pool = OpponentPool.from_calibration_path("runs/archetype_design/bucket_equity_analysis.json")
        # At trajectory start:
        opp = pool.sample_opponent(rng)  # returns ArchetypeProfile or None for self-play
        # At opponent decision node:
        if opp is not None:
            action_dist = pool.policy(opp, ...)
        else:
            action_dist = solver._current_strategy(...)
    """

    def __init__(
        self,
        calibration: EquityCalibration,
        archetypes: tuple[ArchetypeProfile, ...] = NAMED_ARCHETYPES,
        archetype_mix: float = 0.5,
    ):
        """archetype_mix in [0, 1]: probability that a trajectory uses an
        archetype opponent instead of self-play. 0.0 = pure self-play,
        1.0 = no self-play."""
        if not 0.0 <= archetype_mix <= 1.0:
            raise ValueError(f"archetype_mix must be in [0, 1], got {archetype_mix}")
        self.calibration = calibration
        self.archetypes = archetypes
        self.archetype_mix = archetype_mix

    @classmethod
    def from_calibration_path(
        cls,
        path: str | Path,
        archetypes: tuple[ArchetypeProfile, ...] = NAMED_ARCHETYPES,
        archetype_mix: float = 0.5,
    ) -> "OpponentPool":
        return cls(EquityCalibration.load(path), archetypes, archetype_mix)

    def sample_opponent(self, rng: random.Random) -> Optional[ArchetypeProfile]:
        """Return an archetype for this trajectory, or None for self-play."""
        if rng.random() >= self.archetype_mix:
            return None
        return rng.choice(self.archetypes)

    def policy(
        self,
        archetype: ArchetypeProfile,
        *,
        street_idx: int,
        bucket_id: int,
        in_position: bool,
        pot_odds: float,
        stack_to_pot: float,
        legal_mask: np.ndarray,
        facing_bet: bool,
        rng: random.Random,
    ) -> np.ndarray:
        return archetype_policy(
            archetype=archetype,
            calibration=self.calibration,
            street_idx=street_idx,
            bucket_id=bucket_id,
            in_position=in_position,
            pot_odds=pot_odds,
            stack_to_pot=stack_to_pot,
            legal_mask=legal_mask,
            facing_bet=facing_bet,
            rng=rng,
        )
